### ISSUE TITLE
Alert: Hide the close button

### ISSUE THREAD

**Issue by atomtigerzoo** [FriendsOfCake/bootstrap-ui#34]
Is there a way to hide the close button in alerts? It would be nice if there was a way to hide this in all alerts.

**Comment by jadb** [comment]
It should be possible according to [this](https://github.com/FriendsOfCake/bootstrap-ui/blob/master/src/Template/Element/Flash/default.ctp#L5). If you're not using `alert-dismissible` class, the button should not be showing.

If that doesn't work, then let us know and I'll mark it as a bug.

**Comment by ADmad** [comment]
`alert-dismissible` include in the default class [list](https://github.com/FriendsOfCake/bootstrap-ui/blob/master/src/View/Helper/FlashHelper.php#L23). Since user config is merged with default config using Hash::merge() the default classes can't be removed :cry:  Will have to think of an alternative.

**Comment by jadb** [comment]
So wouldn't this not show the button?

```php
echo $this->Flash->render('flash', ['params' => ['class' => ['alert', 'fade', 'in']]]);
```

**Comment by ADmad** [comment]
@jab Using method args would. Just `$this->loadHelper('BootstrapUI.Flash', ['class' => [..]])` won't.  Is that ok?  Considering you generally won't need too many Flash->render() calls.

**Comment by jadb** [comment]
I think it's ok for now, and you're right about now having to use it many times anyways. If one needs to use it for all calls, can just overwrite the template in the app.
