### ISSUE TITLE
Needs buttonhelper

### ISSUE THREAD

**Issue by tgoeminne** [FriendsOfCake/bootstrap-ui#377]
Method BootstrapUI\View\Helper\HtmlHelper::button does not exist

Why is there not a button helper?

**Comment by ndm2** [comment]
Because the form helper has a method for creating buttons (it's the same in the CakePHP core), and nobody ever brought up a need for something else.

Maybe it could make sense to have a method in the HTML helper that generates non-submit type buttons by default, not sure. You can currently achieve it like this (it should be safe to use outside of forms):

```php
echo $this->Form->button('Click me', ['type' => 'button']);
```

**Comment by tgoeminne** [comment]
It would appear they have removed the button from html helper in cakephp 4

**Comment by ADmad** [comment]
`button()` is in `FormHelper`, not `HtmlHelper`.

**Comment by tgoeminne** [comment]
i use the other bootstrap plugin before it had button in html helper... but not updated to cakephp4... but a lot of small things change in cakephp which makes change the code to cake4 annoying. I just wonder what the advantage is of making these small changes like having to add the keyword void, Validator, to tableclasses... or the initialize method...it doesnt add much value imho... anyway going to need to change it use html link instead..

**Comment by ADmad** [comment]
Even in Cake 3 the `button()` method is on the FormHelper not HtmlHelper. So nothing's changed in Cake 4 or this plugin.

Whatever the "other" does is irrelevant to Cake and this plugin.
